package com.l10n.plugin.generator

import com.l10n.plugin.model.L10nFile

object CSharpCodeGenerator {

    fun generate(l10nFile: L10nFile, className: String = "L10nKeys"): String {
        val sb = StringBuilder()

        sb.appendLine("// Auto-generated by L10n Editor")
        sb.appendLine("// Do not modify manually")
        sb.appendLine()
        sb.appendLine("public static class $className")
        sb.appendLine("{")

        for (entry in l10nFile.entries) {
            val key = entry.key
            val keyName = key.replace(".", "_").replace("-", "_")
            val zhText = entry.translations["zh-CN"]?.text ?: ""
            val enText = entry.translations["en-US"]?.text ?: ""

            sb.appendLine("    /// <summary>")
            sb.appendLine("    /// Key: $key")
            sb.appendLine("    /// 中文: $zhText")
            sb.appendLine("    /// English: $enText")
            sb.appendLine("    /// </summary>")
            sb.appendLine("    public const string $keyName = \"$key\";")
            sb.appendLine()
        }

        sb.appendLine("}")
        sb.appendLine()
        sb.appendLine("// Usage:")
        sb.appendLine("// Localization.GetString(L10nKeys.hero)")

        return sb.toString()
    }
}
